// frontend/src/components/ConversationDetail/ConversationDetail.tsx
import React, { useState, useCallback, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Conversation } from '../../types';
import { useAppDispatch } from '../../context/AppContext';
import { useIntro } from '../../context/IntroContext';
import { deleteHistoryItem, updateHistoryItem } from '../../services/api';
import { Card } from '../common/Card';
import { Button } from '../common/Button';
import './ConversationDetail.css';

function formatTime(timestamp: number): string {
  const d = new Date(timestamp);
  const now = new Date();
  const isToday = d.toDateString() === now.toDateString();
  const time = d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  if (isToday) return `Today at ${time}`;
  const yesterday = new Date(now);
  yesterday.setDate(yesterday.getDate() - 1);
  if (d.toDateString() === yesterday.toDateString()) return `Yesterday at ${time}`;
  return `${d.toLocaleDateString([], { month: 'short', day: 'numeric' })} at ${time}`;
}

interface ConversationDetailProps {
  conversation: Conversation;
}

type Tab = 'response' | 'reasoning' | 'sources';

const fadeUp = {
  hidden: { opacity: 0, y: 16 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.4, ease: [0.25, 0.46, 0.45, 0.94] as const },
  },
};

const stagger = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.1, delayChildren: 0.05 },
  },
};

export function ConversationDetail({ conversation }: ConversationDetailProps) {
  const dispatch = useAppDispatch();
  const { contentReady } = useIntro();
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<Tab>('response');
  const [editedText, setEditedText] = useState(conversation.response);
  const [saved, setSaved] = useState(false);
  const [saving, setSaving] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Reset edited text when conversation changes
  useEffect(() => {
    setEditedText(conversation.response);
  }, [conversation.id, conversation.response]);

  // Auto-resize textarea
  const resizeTextarea = useCallback(() => {
    const el = textareaRef.current;
    if (el) {
      el.style.height = 'auto';
      el.style.height = el.scrollHeight + 'px';
    }
  }, []);

  useEffect(() => {
    resizeTextarea();
  }, [editedText, resizeTextarea]);

  const isEdited = editedText !== conversation.response;

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(editedText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {}
  }, [editedText]);

  const handleSave = useCallback(async () => {
    if (saving) return;
    setSaving(true);
    try {
      await updateHistoryItem(conversation.id, editedText);
      dispatch({
        type: 'UPDATE_CONVERSATION_RESPONSE',
        payload: { id: conversation.id, response: editedText },
      });
      setSaved(true);
      setTimeout(() => setSaved(false), 2000);
    } catch {}
    setSaving(false);
  }, [conversation.id, editedText, saving, dispatch]);

  const handleDelete = useCallback(async () => {
    try {
      await deleteHistoryItem(conversation.id);
    } catch {}
    dispatch({ type: 'DELETE_HISTORY_ITEM', payload: conversation.id });
  }, [dispatch, conversation.id]);

  const handleNewQuery = useCallback(() => {
    dispatch({ type: 'NEW_QUERY' });
  }, [dispatch]);

  const handleChange = useCallback((e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setEditedText(e.target.value);
    const el = e.target;
    el.style.height = 'auto';
    el.style.height = el.scrollHeight + 'px';
  }, []);

  const sources = conversation.sources || [];

  return (
    <motion.div
      className="conv-detail"
      variants={stagger}
      initial="hidden"
      animate={contentReady ? "visible" : "hidden"}
      onAnimationComplete={resizeTextarea}
    >
      {/* Top actions */}
      <motion.div className="conv-detail__topbar" variants={fadeUp}>
        <motion.div whileTap={{ scale: 0.97 }}>
          <Button variant="ghost" onClick={handleNewQuery}>
            &larr; New Query
          </Button>
        </motion.div>
        <span className="conv-detail__timestamp">{formatTime(conversation.timestamp)}</span>
      </motion.div>

      {/* Query bubble */}
      <motion.div variants={fadeUp}>
        <Card className="conv-detail__query-card">
          <div className="conv-detail__card-label">
            <span className="conv-detail__label-dot conv-detail__label-dot--query" />
            <span>Customer Query</span>
          </div>
          <p className="conv-detail__query-text">{conversation.query}</p>
          {conversation.customPrompt && (
            <div className="conv-detail__prompt-used">
              <span className="conv-detail__prompt-tag">Custom Prompt</span>
              <span className="conv-detail__prompt-text">{conversation.customPrompt}</span>
            </div>
          )}
        </Card>
      </motion.div>

      {/* Connector line */}
      <motion.div
        className="conv-detail__connector"
        variants={fadeUp}
      >
        <div className="conv-detail__connector-line" />
        <span className="conv-detail__connector-label">AI Generated</span>
        <div className="conv-detail__connector-line" />
      </motion.div>

      {/* Response */}
      <motion.div variants={fadeUp}>
        <Card className="conv-detail__response-card">
          <div className="conv-detail__response-header">
            <div className="conv-detail__tabs">
              <button
                className={`conv-detail__tab ${activeTab === 'response' ? 'conv-detail__tab--active' : ''}`}
                onClick={() => setActiveTab('response')}
              >
                Response
              </button>
              <button
                className={`conv-detail__tab ${activeTab === 'reasoning' ? 'conv-detail__tab--active' : ''}`}
                onClick={() => setActiveTab('reasoning')}
              >
                Reasoning
              </button>
              <button
                className={`conv-detail__tab ${activeTab === 'sources' ? 'conv-detail__tab--active' : ''}`}
                onClick={() => setActiveTab('sources')}
              >
                Sources{sources.length > 0 && ` (${sources.length})`}
              </button>
            </div>
            <div className="conv-detail__response-actions">
              <AnimatePresence>
                {activeTab === 'response' && isEdited && (
                  <motion.div
                    initial={{ opacity: 0, scale: 0.9, x: 8 }}
                    animate={{ opacity: 1, scale: 1, x: 0 }}
                    exit={{ opacity: 0, scale: 0.9, x: 8 }}
                    transition={{ duration: 0.2 }}
                    whileTap={{ scale: 0.95 }}
                  >
                    <Button
                      variant="primary"
                      className="conv-detail__save-btn"
                      onClick={handleSave}
                      disabled={saving}
                    >
                      <AnimatePresence mode="wait">
                        <motion.span
                          key={saved ? 'saved' : saving ? 'saving' : 'save'}
                          initial={{ opacity: 0, y: 4 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={{ opacity: 0, y: -4 }}
                          transition={{ duration: 0.12 }}
                        >
                          {saved ? 'Saved!' : saving ? 'Saving...' : 'Save'}
                        </motion.span>
                      </AnimatePresence>
                    </Button>
                  </motion.div>
                )}
              </AnimatePresence>
              <motion.div whileTap={{ scale: 0.95 }}>
                <Button variant="success" onClick={handleCopy}>
                  <AnimatePresence mode="wait">
                    <motion.span
                      key={copied ? 'done' : 'copy'}
                      initial={{ opacity: 0, y: 4 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -4 }}
                      transition={{ duration: 0.12 }}
                    >
                      {copied ? 'Copied!' : 'Copy'}
                    </motion.span>
                  </AnimatePresence>
                </Button>
              </motion.div>
              <motion.div whileTap={{ scale: 0.95 }}>
                <Button variant="danger" onClick={handleDelete}>
                  Delete
                </Button>
              </motion.div>
            </div>
          </div>

          {activeTab === 'response' && (
            <>
              <textarea
                ref={textareaRef}
                className="conv-detail__response-textarea"
                value={editedText}
                onChange={handleChange}
                spellCheck={false}
              />
              <p className="conv-detail__edit-hint">
                {isEdited ? 'You have unsaved edits — click Save to update' : 'Edit the response above before copying'}
              </p>
            </>
          )}

          {activeTab === 'reasoning' && (
            <div className="conv-detail__reasoning-body">
              {conversation.reasoning || 'No reasoning available for this response.'}
            </div>
          )}

          {activeTab === 'sources' && (
            <div className="conv-detail__sources-body">
              {sources.length === 0 ? (
                <p className="conv-detail__sources-empty">No sources retrieved.</p>
              ) : (
                sources.map((src, i) => (
                  <div key={i} className="conv-detail__source-card">
                    <div className="conv-detail__source-header">
                      <span className="conv-detail__source-badge">{src.category}</span>
                      <span className="conv-detail__source-score">
                        {(src.relevance_score * 100).toFixed(0)}% match
                      </span>
                    </div>
                    <p className="conv-detail__source-desc">{src.description}</p>
                    <p className="conv-detail__source-response">{src.response}</p>
                  </div>
                ))
              )}
            </div>
          )}
        </Card>
      </motion.div>
    </motion.div>
  );
}

// frontend-angular/src/app/features/conversation-detail/conversation-detail.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  ViewChild,
  ViewEncapsulation,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { toSignal } from '@angular/core/rxjs-interop';
import { map } from 'rxjs';

import { AppStateService } from '../../core/services/app-state.service';
import { IntroService } from '../../core/services/intro.service';
import { ButtonComponent } from '../../shared/ui/button.component';
import { CardComponent } from '../../shared/ui/card.component';
import { Conversation } from '../../core/types';

type Tab = 'response' | 'reasoning' | 'sources';

/**
 * Detail view for a single past conversation. Resolves the `:id` route param,
 * looks the conversation up in the AppStateService history signal (which is
 * the same source the sidebar reads from — no extra API call), and renders
 * the same tabbed editor as the GenerateView's response panel, plus a
 * delete action.
 */
@Component({
  selector: 'app-conversation-detail',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  imports: [ButtonComponent, CardComponent],
  styleUrl: './conversation-detail.component.css',
  template: `
    @if (conversation(); as conv) {
      <div class="conv-detail" [class.conv-detail--ready]="intro.contentReady()">
        <!-- Top actions -->
        <div class="conv-detail__topbar conv-detail__stagger-1">
          <app-button variant="ghost" (click)="onNewQuery()">
            ← New Query
          </app-button>
          <span class="conv-detail__timestamp">{{ formatTime(conv.timestamp) }}</span>
        </div>

        <!-- Query bubble -->
        <div class="conv-detail__stagger-2">
          <app-card variant="conv-detail__query-card">
            <div class="conv-detail__card-label">
              <span class="conv-detail__label-dot conv-detail__label-dot--query"></span>
              <span>Customer Query</span>
            </div>
            <p class="conv-detail__query-text">{{ conv.query }}</p>
            @if (conv.customPrompt) {
              <div class="conv-detail__prompt-used">
                <span class="conv-detail__prompt-tag">Custom Prompt</span>
                <span class="conv-detail__prompt-text">{{ conv.customPrompt }}</span>
              </div>
            }
          </app-card>
        </div>

        <!-- Connector line -->
        <div class="conv-detail__connector conv-detail__stagger-3">
          <div class="conv-detail__connector-line"></div>
          <span class="conv-detail__connector-label">AI Generated</span>
          <div class="conv-detail__connector-line"></div>
        </div>

        <!-- Response card -->
        <div class="conv-detail__stagger-4">
          <app-card variant="conv-detail__response-card">
            <div class="conv-detail__response-header">
              <div class="conv-detail__tabs">
                <button
                  type="button"
                  class="conv-detail__tab"
                  [class.conv-detail__tab--active]="activeTab() === 'response'"
                  (click)="activeTab.set('response')"
                >
                  Response
                </button>
                <button
                  type="button"
                  class="conv-detail__tab"
                  [class.conv-detail__tab--active]="activeTab() === 'reasoning'"
                  (click)="activeTab.set('reasoning')"
                >
                  Reasoning
                </button>
                <button
                  type="button"
                  class="conv-detail__tab"
                  [class.conv-detail__tab--active]="activeTab() === 'sources'"
                  (click)="activeTab.set('sources')"
                >
                  Sources@if (sourcesCount() > 0) { ({{ sourcesCount() }}) }
                </button>
              </div>
              <div class="conv-detail__response-actions">
                @if (activeTab() === 'response' && isEdited()) {
                  <app-button
                    variant="primary"
                    [disabled]="saving()"
                    (click)="onSave(conv.id)"
                  >
                    {{ saved() ? 'Saved!' : saving() ? 'Saving...' : 'Save' }}
                  </app-button>
                }
                <app-button variant="success" (click)="onCopy()">
                  {{ copied() ? 'Copied!' : 'Copy' }}
                </app-button>
                <app-button variant="danger" (click)="onDelete(conv.id)">
                  Delete
                </app-button>
              </div>
            </div>

            @switch (activeTab()) {
              @case ('response') {
                <textarea
                  #textarea
                  class="conv-detail__response-textarea"
                  spellcheck="false"
                  [value]="editedText()"
                  (input)="onInput($event)"
                ></textarea>
                <p class="conv-detail__edit-hint">
                  {{
                    isEdited()
                      ? 'You have unsaved edits — click Save to update'
                      : 'Edit the response above before copying'
                  }}
                </p>
              }
              @case ('reasoning') {
                <div class="conv-detail__reasoning-body">
                  {{ conv.reasoning || 'No reasoning available for this response.' }}
                </div>
              }
              @case ('sources') {
                <div class="conv-detail__sources-body">
                  @if (sourcesCount() === 0) {
                    <p class="conv-detail__sources-empty">No sources retrieved.</p>
                  } @else {
                    @for (src of conv.sources; track $index) {
                      <div class="conv-detail__source-card">
                        <div class="conv-detail__source-header">
                          <span class="conv-detail__source-badge">{{ src.category }}</span>
                          <span class="conv-detail__source-score">
                            {{ (src.relevance_score * 100).toFixed(0) }}% match
                          </span>
                        </div>
                        <p class="conv-detail__source-desc">{{ src.description }}</p>
                        <p class="conv-detail__source-response">{{ src.response }}</p>
                      </div>
                    }
                  }
                </div>
              }
            }
          </app-card>
        </div>
      </div>
    } @else {
      <div class="conv-detail conv-detail--missing">
        <p class="conv-detail__missing-text">Conversation not found.</p>
        <app-button variant="ghost" (click)="onNewQuery()">← New Query</app-button>
      </div>
    }
  `,
})
export class ConversationDetailComponent implements AfterViewInit {
  protected state = inject(AppStateService);
  protected intro = inject(IntroService);
  private route = inject(ActivatedRoute);
  private cdr = inject(ChangeDetectorRef);

  @ViewChild('textarea') textareaRef?: ElementRef<HTMLTextAreaElement>;

  private routeId = toSignal(
    this.route.paramMap.pipe(map((p) => p.get('id'))),
    { initialValue: null as string | null },
  );

  protected conversation = computed<Conversation | null>(() => {
    const id = this.routeId();
    if (!id) return null;
    return this.state.history().find((c) => c.id === id) ?? null;
  });

  protected sourcesCount = computed(
    () => this.conversation()?.sources?.length ?? 0,
  );

  protected activeTab = signal<Tab>('response');
  protected editedText = signal<string>('');
  protected copied = signal(false);
  protected saved = signal(false);
  protected saving = signal(false);

  protected isEdited = computed(
    () => this.editedText() !== (this.conversation()?.response ?? ''),
  );

  constructor() {
    // Sync editedText whenever the resolved conversation changes (route swap
    // or after a save propagates new state).
    effect(() => {
      const conv = this.conversation();
      if (conv) {
        this.editedText.set(conv.response);
        queueMicrotask(() => this.autoResize());
      }
    });

    // Make sure history is loaded so the lookup succeeds on direct deep-link.
    if (this.state.history().length === 0) {
      void this.state.loadHistory();
    }
  }

  ngAfterViewInit(): void {
    this.autoResize();
  }

  private autoResize(): void {
    const el = this.textareaRef?.nativeElement;
    if (!el) return;
    el.style.height = 'auto';
    el.style.height = `${el.scrollHeight}px`;
  }

  onInput(event: Event): void {
    const el = event.target as HTMLTextAreaElement;
    this.editedText.set(el.value);
    el.style.height = 'auto';
    el.style.height = `${el.scrollHeight}px`;
  }

  async onCopy(): Promise<void> {
    try {
      await navigator.clipboard.writeText(this.editedText());
      this.copied.set(true);
      setTimeout(() => {
        this.copied.set(false);
        this.cdr.markForCheck();
      }, 2000);
    } catch {
      this.textareaRef?.nativeElement.select();
    }
  }

  async onSave(id: string): Promise<void> {
    if (this.saving()) return;
    this.saving.set(true);
    try {
      await this.state.updateConversationResponse(id, this.editedText());
      this.saved.set(true);
      setTimeout(() => {
        this.saved.set(false);
        this.cdr.markForCheck();
      }, 2000);
    } catch {
      /* ignore */
    } finally {
      this.saving.set(false);
    }
  }

  async onDelete(id: string): Promise<void> {
    await this.state.deleteConversation(id);
  }

  onNewQuery(): void {
    this.state.newQuery();
  }

  formatTime(timestamp: number): string {
    const d = new Date(timestamp);
    const now = new Date();
    const time = d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    if (d.toDateString() === now.toDateString()) return `Today at ${time}`;
    const yesterday = new Date(now);
    yesterday.setDate(yesterday.getDate() - 1);
    if (d.toDateString() === yesterday.toDateString()) return `Yesterday at ${time}`;
    return `${d.toLocaleDateString([], { month: 'short', day: 'numeric' })} at ${time}`;
  }
}
