// frontend/src/components/QueryInput/QueryInput.tsx
import React, { useCallback, useRef } from 'react';
import { useAppState, useAppDispatch } from '../../context/AppContext';
import './QueryInput.css';

export function QueryInput() {
  const { query } = useAppState();
  const dispatch = useAppDispatch();
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const handleChange = useCallback((e: React.ChangeEvent<HTMLTextAreaElement>) => {
    dispatch({ type: 'SET_QUERY', payload: e.target.value });
    const el = e.target;
    el.style.height = 'auto';
    el.style.height = el.scrollHeight + 'px';
  }, [dispatch]);

  return (
    <div className="query-input">
      <label className="query-input__label" htmlFor="query-textarea">
        Customer Query
      </label>
      <textarea
        ref={textareaRef}
        id="query-textarea"
        className="query-input__textarea"
        placeholder="Paste the customer's query here..."
        value={query}
        onChange={handleChange}
        rows={4}
        spellCheck={false}
      />
    </div>
  );
}

// frontend/src/app/shared/query-input/query-input.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ViewEncapsulation,
  inject,
} from '@angular/core';
import { AppStateService } from '../../core/services/app-state.service';

@Component({
  selector: 'app-query-input',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  styleUrl: './query-input.component.css',
  template: `
    <div class="query-input">
      <label class="query-input__label" for="query-textarea">Customer Query</label>
      <textarea
        id="query-textarea"
        class="query-input__textarea"
        placeholder="Paste the customer's query here..."
        rows="4"
        spellcheck="false"
        [value]="state.query()"
        (input)="onInput($event)"
      ></textarea>
    </div>
  `,
})
export class QueryInputComponent {
  protected state = inject(AppStateService);

  onInput(event: Event): void {
    const el = event.target as HTMLTextAreaElement;
    this.state.setQuery(el.value);
    el.style.height = 'auto';
    el.style.height = `${el.scrollHeight}px`;
  }
}
