// frontend/src/components/PromptInput/PromptInput.tsx
import React, { useCallback } from 'react';
import { useAppState, useAppDispatch } from '../../context/AppContext';
import './PromptInput.css';

export function PromptInput() {
  const { customPrompt } = useAppState();
  const dispatch = useAppDispatch();

  const handleChange = useCallback((e: React.ChangeEvent<HTMLTextAreaElement>) => {
    dispatch({ type: 'SET_CUSTOM_PROMPT', payload: e.target.value });
    const el = e.target;
    el.style.height = 'auto';
    el.style.height = el.scrollHeight + 'px';
  }, [dispatch]);

  return (
    <div className="prompt-input">
      <label className="prompt-input__label" htmlFor="prompt-textarea">
        Custom Prompt
      </label>
      <textarea
        id="prompt-textarea"
        className="prompt-input__textarea"
        placeholder="Add specific instructions for the AI..."
        value={customPrompt}
        onChange={handleChange}
        rows={2}
        spellCheck={false}
      />
    </div>
  );
}

// frontend-angular/src/app/shared/prompt-input/prompt-input.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ViewEncapsulation,
  inject,
} from '@angular/core';
import { AppStateService } from '../../core/services/app-state.service';

@Component({
  selector: 'app-prompt-input',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  styleUrl: './prompt-input.component.css',
  template: `
    <div class="prompt-input">
      <label class="prompt-input__label" for="prompt-textarea">Custom Prompt</label>
      <textarea
        id="prompt-textarea"
        class="prompt-input__textarea"
        placeholder="Add specific instructions for the AI..."
        rows="2"
        spellcheck="false"
        [value]="state.customPrompt()"
        (input)="onInput($event)"
      ></textarea>
    </div>
  `,
})
export class PromptInputComponent {
  protected state = inject(AppStateService);

  onInput(event: Event): void {
    const el = event.target as HTMLTextAreaElement;
    this.state.setCustomPrompt(el.value);
    el.style.height = 'auto';
    el.style.height = `${el.scrollHeight}px`;
  }
}
