// frontend/src/components/ActionBar/ActionBar.tsx
import React, { useCallback } from 'react';
import { motion } from 'framer-motion';
import { useAppState, useAppDispatch } from '../../context/AppContext';
import { generateResponse } from '../../services/api';
import { Button } from '../common/Button';
import { Toggle } from '../common/Toggle';
import './ActionBar.css';

export function ActionBar() {
  const { query, response, isLoading, promptModeEnabled, customPrompt } = useAppState();
  const dispatch = useAppDispatch();

  const handleGenerate = useCallback(async () => {
    if (!query.trim() || isLoading) return;
    dispatch({ type: 'GENERATE_START' });
    try {
      const result = await generateResponse(
        query,
        promptModeEnabled ? customPrompt : undefined
      );
      dispatch({ type: 'GENERATE_SUCCESS', payload: result });
    } catch {
      dispatch({ type: 'CLEAR_RESPONSE' });
    }
  }, [query, isLoading, promptModeEnabled, customPrompt, dispatch]);

  const handleToggle = useCallback(() => {
    dispatch({ type: 'TOGGLE_PROMPT_MODE' });
  }, [dispatch]);

  const hasResponse = response.length > 0;

  return (
    <div className="action-bar">
      <div className="action-bar__left">
        {!hasResponse ? (
          <motion.div whileTap={{ scale: 0.97 }} whileHover={{ scale: 1.01 }}>
            <Button
              variant="primary"
              onClick={handleGenerate}
              disabled={!query.trim() || isLoading}
            >
              Generate Response
            </Button>
          </motion.div>
        ) : (
          <>
            <motion.div whileTap={{ scale: 0.97 }}>
              <Button
                variant="danger"
                onClick={handleGenerate}
                disabled={!query.trim() || isLoading}
              >
                Regenerate
              </Button>
            </motion.div>
            <motion.div whileTap={{ scale: 0.97 }}>
              <Button
                variant="ghost"
                onClick={() => dispatch({ type: 'CLEAR_RESPONSE' })}
              >
                Clear
              </Button>
            </motion.div>
          </>
        )}
      </div>
      <div className="action-bar__right">
        <Toggle
          checked={promptModeEnabled}
          onChange={handleToggle}
          label="Prompt Mode"
        />
      </div>
    </div>
  );
}

// frontend-angular/src/app/shared/action-bar/action-bar.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ViewEncapsulation,
  computed,
  inject,
} from '@angular/core';
import { AppStateService } from '../../core/services/app-state.service';
import { ButtonComponent } from '../ui/button.component';
import { ToggleComponent } from '../ui/toggle.component';

@Component({
  selector: 'app-action-bar',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  imports: [ButtonComponent, ToggleComponent],
  styleUrl: './action-bar.component.css',
  template: `
    <div class="action-bar">
      <div class="action-bar__left">
        @if (!hasResponse()) {
          <app-button
            variant="primary"
            [disabled]="!canGenerate()"
            (click)="onGenerate()"
          >
            Generate Response
          </app-button>
        } @else {
          <app-button
            variant="danger"
            [disabled]="!canGenerate()"
            (click)="onGenerate()"
          >
            Regenerate
          </app-button>
          <app-button variant="ghost" (click)="onClear()">Clear</app-button>
        }
      </div>
      <div class="action-bar__right">
        <app-toggle
          [checked]="state.promptModeEnabled()"
          label="Prompt Mode"
          (checkedChange)="onTogglePromptMode()"
        />
      </div>
    </div>
  `,
})
export class ActionBarComponent {
  protected state = inject(AppStateService);

  protected hasResponse = computed(() => this.state.response().length > 0);
  protected canGenerate = computed(
    () => this.state.query().trim().length > 0 && !this.state.isLoading(),
  );

  async onGenerate(): Promise<void> {
    if (!this.canGenerate()) return;
    await this.state.generate();
  }

  onClear(): void {
    this.state.clearResponse();
  }

  onTogglePromptMode(): void {
    this.state.togglePromptMode();
  }
}
