// frontend-angular/src/app/shared/ui/toggle.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ViewEncapsulation,
  input,
  output,
} from '@angular/core';

@Component({
  selector: 'app-toggle',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  styleUrl: './toggle.component.css',
  template: `
    <button
      type="button"
      class="toggle"
      role="switch"
      [attr.aria-checked]="checked()"
      (click)="toggle()"
    >
      <span class="toggle__track" [class.toggle__track--active]="checked()">
        <span class="toggle__thumb"></span>
      </span>
      <span class="toggle__label" [class.toggle__label--active]="checked()">
        {{ label() }}
      </span>
    </button>
  `,
})
export class ToggleComponent {
  checked = input<boolean>(false);
  label = input.required<string>();
  checkedChange = output<boolean>();

  toggle(): void {
    this.checkedChange.emit(!this.checked());
  }
}

// frontend/src/components/common/Toggle.tsx
import React from 'react';
import { motion } from 'framer-motion';
import './Toggle.css';

interface ToggleProps {
  checked: boolean;
  onChange: () => void;
  label: string;
}

export function Toggle({ checked, onChange, label }: ToggleProps) {
  return (
    <button
      className="toggle"
      role="switch"
      aria-checked={checked}
      onClick={onChange}
      type="button"
    >
      <span className={`toggle__track ${checked ? 'toggle__track--active' : ''}`}>
        <motion.span
          className="toggle__thumb"
          layout
          transition={{ type: 'spring', stiffness: 500, damping: 30 }}
        />
      </span>
      <span className={`toggle__label ${checked ? 'toggle__label--active' : ''}`}>{label}</span>
    </button>
  );
}
