// frontend/src/components/AnalyticsDashboard/TokenUsageTab.tsx
import React, { useEffect, useState } from 'react';
import {
  ComposedChart, Bar, Line, XAxis, YAxis, CartesianGrid,
  Tooltip, ResponsiveContainer, PieChart, Pie, Cell,
} from 'recharts';
import type { PieLabelRenderProps } from 'recharts';
import { TokenUsagePoint, TokenByUser } from '../../types';
import { fetchTokenUsage, fetchTokenByUser } from '../../services/api';
import { useChartTheme } from './chartTheme';
import { StatCard } from './components/StatCard';
import './TokenUsageTab.css';

export function TokenUsageTab() {
  const [usage, setUsage] = useState<TokenUsagePoint[]>([]);
  const [byUser, setByUser] = useState<TokenByUser[]>([]);
  const chart = useChartTheme();

  useEffect(() => {
    fetchTokenUsage({}).then(setUsage).catch(() => {});
    fetchTokenByUser().then(setByUser).catch(() => {});
  }, []);

  const totalPrompt = usage.reduce((s, u) => s + u.prompt_tokens, 0);
  const totalCompletion = usage.reduce((s, u) => s + u.completion_tokens, 0);
  const totalRequests = usage.reduce((s, u) => s + u.request_count, 0);
  const totalTokens = usage.reduce((s, u) => s + u.total_tokens, 0);

  const pieData = [
    { name: 'Prompt', value: totalPrompt },
    { name: 'Completion', value: totalCompletion },
  ].filter((d) => d.value > 0);

  const pieColors = [chart.colors.primary, chart.colors.secondary];

  return (
    <div className="token-tab">
      <div className="token-tab__cards">
        <StatCard label="Total Tokens" value={totalTokens} format="compact" />
        <StatCard label="Total Requests" value={totalRequests} />
        <StatCard label="Avg Tokens / Request" value={totalRequests > 0 ? Math.round(totalTokens / totalRequests) : 0} />
      </div>

      <div className="token-tab__charts-row">
        {/* Token trend */}
        <div className="token-tab__chart-card token-tab__chart-card--wide">
          <h3 className="token-tab__chart-title">Token Usage Over Time</h3>
          <ResponsiveContainer width="100%" height={280}>
            <ComposedChart data={usage} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" stroke={chart.colors.grid} />
              <XAxis
                dataKey="date"
                tick={{ fill: chart.colors.textLight, fontSize: 11 }}
                tickFormatter={(d: string) => d.slice(5)}
                stroke={chart.colors.grid}
              />
              <YAxis yAxisId="tokens" tick={{ fill: chart.colors.textLight, fontSize: 11 }} stroke={chart.colors.grid} />
              <YAxis yAxisId="requests" orientation="right" tick={{ fill: chart.colors.textLight, fontSize: 11 }} stroke={chart.colors.grid} />
              <Tooltip
                contentStyle={{
                  background: chart.colors.tooltip,
                  border: `1px solid ${chart.colors.tooltipBorder}`,
                  borderRadius: 8, fontSize: 13, color: chart.colors.text,
                }}
              />
              <Bar yAxisId="requests" dataKey="request_count" name="Requests" fill={chart.colors.secondary} opacity={0.6} radius={[3, 3, 0, 0]} />
              <Line yAxisId="tokens" type="monotone" dataKey="total_tokens" name="Tokens" stroke={chart.colors.primary} strokeWidth={2} dot={false} />
            </ComposedChart>
          </ResponsiveContainer>
        </div>

        {/* Token breakdown pie */}
        <div className="token-tab__chart-card token-tab__chart-card--narrow">
          <h3 className="token-tab__chart-title">Token Breakdown</h3>
          {pieData.length > 0 ? (
            <ResponsiveContainer width="100%" height={280}>
              <PieChart>
                <Pie
                  data={pieData}
                  cx="50%" cy="50%"
                  innerRadius={60} outerRadius={90}
                  paddingAngle={3}
                  dataKey="value"
                  label={(props: PieLabelRenderProps) => `${props.name ?? ''} ${((Number(props.percent ?? 0)) * 100).toFixed(0)}%`}
                >
                  {pieData.map((_, idx) => (
                    <Cell key={idx} fill={pieColors[idx % pieColors.length]} />
                  ))}
                </Pie>
                <Tooltip
                  contentStyle={{
                    background: chart.colors.tooltip,
                    border: `1px solid ${chart.colors.tooltipBorder}`,
                    borderRadius: 8, fontSize: 13, color: chart.colors.text,
                  }}
                  formatter={(value: unknown) => String(Number(value ?? 0).toLocaleString())}
                />
              </PieChart>
            </ResponsiveContainer>
          ) : (
            <div className="token-tab__empty">No data yet</div>
          )}
        </div>
      </div>

      {/* Top users table */}
      <div className="token-tab__section">
        <h3 className="token-tab__chart-title">Top Users by Token Usage</h3>
        <div className="token-tab__table">
          <div className="token-tab__header-row">
            <span>User</span>
            <span>Total Tokens</span>
            <span>Requests</span>
            <span>Avg / Request</span>
          </div>
          {byUser.map((u) => {
            const maxTokens = byUser[0]?.total_tokens || 1;
            const pct = Math.round((u.total_tokens / maxTokens) * 100);
            return (
              <div key={u.user_id} className="token-tab__row">
                <span className="token-tab__cell">{u.user_email || u.user_id}</span>
                <span className="token-tab__cell">
                  <span className="token-tab__bar-wrapper">
                    <span className="token-tab__bar" style={{ width: `${pct}%` }} />
                    <span className="token-tab__bar-label">{u.total_tokens.toLocaleString()}</span>
                  </span>
                </span>
                <span className="token-tab__cell">{u.request_count}</span>
                <span className="token-tab__cell">{Math.round(u.avg_tokens_per_request).toLocaleString()}</span>
              </div>
            );
          })}
          {byUser.length === 0 && (
            <div className="token-tab__empty">No usage data</div>
          )}
        </div>
      </div>
    </div>
  );
}

// frontend-angular/src/app/features/analytics/token-usage-tab.component.ts
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ViewEncapsulation,
  computed,
  inject,
  signal,
} from '@angular/core';
import { firstValueFrom } from 'rxjs';
import { NgxChartsModule } from '@swimlane/ngx-charts';
import { curveMonotoneX } from 'd3-shape';

import { ApiService } from '../../core/services/api.service';
import { TokenByUser, TokenUsagePoint } from '../../core/types';
import { ChartThemeService } from './chart-theme';
import { StatCardComponent } from './stat-card/stat-card.component';

interface BarPoint {
  name: string;
  value: number;
}

interface LineSeries {
  name: string;
  series: BarPoint[];
}

interface TopUserRow {
  user: TokenByUser;
  pct: number;
}

/**
 * Token Usage tab — three StatCards, a combo chart (bar = requests,
 * line = total tokens), a pie chart for prompt vs completion split,
 * and a top-users table with a gradient bar indicator. ngx-charts
 * doesn't have a true ComposedChart, so we render the bar chart and
 * line chart in the same wrapper with absolute positioning so they
 * share the same x-axis space — close enough to the Recharts version.
 */
@Component({
  selector: 'app-token-usage-tab',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  imports: [NgxChartsModule, StatCardComponent],
  styleUrl: './token-usage-tab.component.css',
  template: `
    <div class="token-tab">
      <div class="token-tab__cards">
        <app-stat-card
          label="Total Tokens"
          [value]="totalTokens()"
          format="compact"
        />
        <app-stat-card label="Total Requests" [value]="totalRequests()" />
        <app-stat-card label="Avg Tokens / Request" [value]="avgTokensPerRequest()" />
      </div>

      <div class="token-tab__charts-row">
        <!-- Token usage trend (bar+line combo) -->
        <div class="token-tab__chart-card token-tab__chart-card--wide">
          <h3 class="token-tab__chart-title">Token Usage Over Time</h3>
          @if (usage().length > 0) {
            <div class="token-tab__chart-stack">
              <ngx-charts-bar-vertical
                class="token-tab__chart-layer"
                [results]="barData()"
                [scheme]="barScheme()"
                [xAxis]="true"
                [yAxis]="true"
                [showXAxisLabel]="false"
                [showYAxisLabel]="false"
                [barPadding]="6"
                [roundEdges]="true"
              ></ngx-charts-bar-vertical>
              <ngx-charts-line-chart
                class="token-tab__chart-layer token-tab__chart-layer--overlay"
                [results]="lineData()"
                [scheme]="lineScheme()"
                [xAxis]="false"
                [yAxis]="false"
                [autoScale]="true"
                [curve]="curve"
              ></ngx-charts-line-chart>
            </div>
          } @else {
            <div class="token-tab__empty">No data yet</div>
          }
        </div>

        <!-- Prompt vs completion split -->
        <div class="token-tab__chart-card token-tab__chart-card--narrow">
          <h3 class="token-tab__chart-title">Token Breakdown</h3>
          @if (pieData().length > 0) {
            <div class="token-tab__pie">
              <ngx-charts-advanced-pie-chart
                [results]="pieData()"
                [scheme]="pieScheme()"
              ></ngx-charts-advanced-pie-chart>
            </div>
          } @else {
            <div class="token-tab__empty">No data yet</div>
          }
        </div>
      </div>

      <!-- Top users by token usage -->
      <div class="token-tab__section">
        <h3 class="token-tab__chart-title">Top Users by Token Usage</h3>
        <div class="token-tab__table">
          <div class="token-tab__header-row">
            <span>User</span>
            <span>Total Tokens</span>
            <span>Requests</span>
            <span>Avg / Request</span>
          </div>
          @for (row of topUsers(); track row.user.user_id) {
            <div class="token-tab__row">
              <span class="token-tab__cell">
                {{ row.user.user_email || row.user.user_id }}
              </span>
              <span class="token-tab__cell">
                <span class="token-tab__bar-wrapper">
                  <span
                    class="token-tab__bar"
                    [style.width.%]="row.pct"
                  ></span>
                  <span class="token-tab__bar-label">
                    {{ row.user.total_tokens.toLocaleString() }}
                  </span>
                </span>
              </span>
              <span class="token-tab__cell">{{ row.user.request_count }}</span>
              <span class="token-tab__cell">
                {{ formatAvg(row.user.avg_tokens_per_request) }}
              </span>
            </div>
          }
          @if (topUsers().length === 0) {
            <div class="token-tab__empty">No usage data</div>
          }
        </div>
      </div>
    </div>
  `,
})
export class TokenUsageTabComponent {
  private api = inject(ApiService);
  private chartTheme = inject(ChartThemeService);
  private cdr = inject(ChangeDetectorRef);

  protected usage = signal<TokenUsagePoint[]>([]);
  protected byUser = signal<TokenByUser[]>([]);

  protected readonly curve = curveMonotoneX;

  // ── Aggregated stats ──
  protected totalPrompt = computed(() =>
    this.usage().reduce((s, u) => s + u.prompt_tokens, 0),
  );

  protected totalCompletion = computed(() =>
    this.usage().reduce((s, u) => s + u.completion_tokens, 0),
  );

  protected totalRequests = computed(() =>
    this.usage().reduce((s, u) => s + u.request_count, 0),
  );

  protected totalTokens = computed(() =>
    this.usage().reduce((s, u) => s + u.total_tokens, 0),
  );

  protected avgTokensPerRequest = computed(() => {
    const reqs = this.totalRequests();
    return reqs > 0 ? Math.round(this.totalTokens() / reqs) : 0;
  });

  // ── Chart data ──
  protected barData = computed<BarPoint[]>(() =>
    this.usage().map((u) => ({
      name: u.date.slice(5),
      value: u.request_count,
    })),
  );

  protected lineData = computed<LineSeries[]>(() => [
    {
      name: 'Tokens',
      series: this.usage().map((u) => ({
        name: u.date.slice(5),
        value: u.total_tokens,
      })),
    },
  ]);

  protected pieData = computed(() =>
    [
      { name: 'Prompt', value: this.totalPrompt() },
      { name: 'Completion', value: this.totalCompletion() },
    ].filter((d) => d.value > 0),
  );

  // ── Top users with bar percentages ──
  protected topUsers = computed<TopUserRow[]>(() => {
    const users = this.byUser();
    if (users.length === 0) return [];
    const max = users[0]?.total_tokens || 1;
    return users.map((u) => ({
      user: u,
      pct: Math.round((u.total_tokens / max) * 100),
    }));
  });

  // ── Color schemes (recompute on theme change) ──
  protected barScheme = computed(() => {
    const c = this.chartTheme.colors();
    return this.chartTheme.schemeFor([c.secondary]);
  });

  protected lineScheme = computed(() => {
    const c = this.chartTheme.colors();
    return this.chartTheme.schemeFor([c.primary]);
  });

  protected pieScheme = computed(() => {
    const c = this.chartTheme.colors();
    return this.chartTheme.schemeFor([c.primary, c.secondary]);
  });

  protected formatAvg(n: number): string {
    return Math.round(n).toLocaleString();
  }

  constructor() {
    void this.load();
  }

  private async load(): Promise<void> {
    try {
      const [usage, byUser] = await Promise.all([
        firstValueFrom(this.api.fetchTokenUsage({})),
        firstValueFrom(this.api.fetchTokenByUser()),
      ]);
      this.usage.set(usage);
      this.byUser.set(byUser);
    } catch {
      /* ignore */
    } finally {
      this.cdr.markForCheck();
    }
  }
}
