// frontend/src/components/common/LoadingSpinner.tsx
import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import './LoadingSpinner.css';

const STATUS_WORDS = [
  'Thinking',
  'Analyzing Query',
  'Searching Knowledge Base',
  'Retrieving Sources',
  'Generating Response',
  'Crafting Reply',
];

const CYCLE_MS = 2400;

const NUM_ORBS = 5;
const orbs = Array.from({ length: NUM_ORBS }, (_, i) => i);
const NUM_PARTICLES = 8;
const particles = Array.from({ length: NUM_PARTICLES }, (_, i) => i);

export function LoadingSpinner() {
  const [wordIndex, setWordIndex] = useState(0);

  useEffect(() => {
    const id = setInterval(() => {
      setWordIndex((prev) => (prev + 1) % STATUS_WORDS.length);
    }, CYCLE_MS);
    return () => clearInterval(id);
  }, []);

  return (
    <div className="loader" role="status" aria-label="Generating response">
      {/* Ambient glow behind everything */}
      <div className="loader__ambient" />

      {/* Orbital ring system */}
      <div className="loader__orb-system">
        {/* Outer ring */}
        <motion.div
          className="loader__ring loader__ring--outer"
          animate={{ rotate: 360 }}
          transition={{ duration: 8, ease: 'linear', repeat: Infinity }}
        />

        {/* Inner ring — counter-rotate */}
        <motion.div
          className="loader__ring loader__ring--inner"
          animate={{ rotate: -360 }}
          transition={{ duration: 5, ease: 'linear', repeat: Infinity }}
        />

        {/* Floating orbs on the outer ring */}
        {orbs.map((i) => (
          <motion.div
            key={i}
            className="loader__orb-wrapper"
            animate={{ rotate: 360 }}
            transition={{
              duration: 4 + i * 0.8,
              ease: 'linear',
              repeat: Infinity,
              delay: i * 0.3,
            }}
          >
            <motion.div
              className="loader__orb"
              animate={{
                scale: [1, 1.5, 1],
                opacity: [0.6, 1, 0.6],
              }}
              transition={{
                duration: 2 + i * 0.4,
                ease: 'easeInOut',
                repeat: Infinity,
                delay: i * 0.2,
              }}
              style={{
                width: 4 + (i % 3) * 2,
                height: 4 + (i % 3) * 2,
              }}
            />
          </motion.div>
        ))}

        {/* Center pulse */}
        <motion.div
          className="loader__center"
          animate={{
            scale: [1, 1.2, 1],
            boxShadow: [
              '0 0 20px var(--color-accent-glow), 0 0 40px var(--color-accent-subtle)',
              '0 0 30px var(--color-accent-intense), 0 0 60px var(--color-accent-glow)',
              '0 0 20px var(--color-accent-glow), 0 0 40px var(--color-accent-subtle)',
            ],
          }}
          transition={{ duration: 2, ease: 'easeInOut', repeat: Infinity }}
        />

        {/* Sparkle particles */}
        {particles.map((i) => {
          const angle = (i / NUM_PARTICLES) * 360;
          const radius = 44 + (i % 3) * 8;
          return (
            <motion.div
              key={`p-${i}`}
              className="loader__particle"
              style={{
                left: '50%',
                top: '50%',
              }}
              animate={{
                x: [
                  Math.cos((angle * Math.PI) / 180) * radius,
                  Math.cos(((angle + 60) * Math.PI) / 180) * (radius + 10),
                  Math.cos(((angle + 120) * Math.PI) / 180) * radius,
                ],
                y: [
                  Math.sin((angle * Math.PI) / 180) * radius,
                  Math.sin(((angle + 60) * Math.PI) / 180) * (radius + 10),
                  Math.sin(((angle + 120) * Math.PI) / 180) * radius,
                ],
                opacity: [0, 0.8, 0],
                scale: [0, 1, 0],
              }}
              transition={{
                duration: 3 + (i % 3),
                ease: 'easeInOut',
                repeat: Infinity,
                delay: i * 0.4,
              }}
            />
          );
        })}
      </div>

      {/* Status text with word cycling */}
      <div className="loader__status">
        <AnimatePresence mode="wait">
          <motion.span
            key={wordIndex}
            className="loader__word"
            initial={{ opacity: 0, y: 12, filter: 'blur(4px)' }}
            animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
            exit={{ opacity: 0, y: -12, filter: 'blur(4px)' }}
            transition={{ duration: 0.4, ease: [0.25, 0.46, 0.45, 0.94] }}
          >
            {STATUS_WORDS[wordIndex]}
          </motion.span>
        </AnimatePresence>

        {/* Animated dots */}
        <span className="loader__dots">
          {[0, 1, 2].map((i) => (
            <motion.span
              key={i}
              className="loader__dot-char"
              animate={{ opacity: [0, 1, 0] }}
              transition={{
                duration: 1.2,
                ease: 'easeInOut',
                repeat: Infinity,
                delay: i * 0.2,
              }}
            >
              .
            </motion.span>
          ))}
        </span>
      </div>

      {/* Shimmer progress bar */}
      <div className="loader__progress">
        <motion.div
          className="loader__progress-fill"
          animate={{
            x: ['-100%', '200%'],
          }}
          transition={{
            duration: 2,
            ease: [0.25, 0.46, 0.45, 0.94],
            repeat: Infinity,
            repeatDelay: 0.3,
          }}
        />
      </div>
    </div>
  );
}

// frontend/src/app/shared/ui/loading-spinner.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  OnInit,
  ViewEncapsulation,
  inject,
  signal,
} from '@angular/core';

const STATUS_WORDS = [
  'Thinking',
  'Analyzing Query',
  'Searching Knowledge Base',
  'Retrieving Sources',
  'Generating Response',
  'Crafting Reply',
] as const;

const CYCLE_MS = 2400;
const NUM_ORBS = 5;
const NUM_PARTICLES = 8;

interface ParticleStyle {
  index: number;
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  x3: number;
  y3: number;
  duration: number;
  delay: number;
}

@Component({
  selector: 'app-loading-spinner',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  styleUrl: './loading-spinner.component.css',
  template: `
    <div class="loader" role="status" aria-label="Generating response">
      <div class="loader__ambient"></div>

      <div class="loader__orb-system">
        <div class="loader__ring loader__ring--outer"></div>
        <div class="loader__ring loader__ring--inner"></div>

        @for (i of orbIndices; track i) {
          <div
            class="loader__orb-wrapper"
            [style.animation-duration.s]="4 + i * 0.8"
            [style.animation-delay.s]="i * 0.3"
          >
            <div
              class="loader__orb"
              [style.width.px]="4 + (i % 3) * 2"
              [style.height.px]="4 + (i % 3) * 2"
              [style.animation-duration.s]="2 + i * 0.4"
              [style.animation-delay.s]="i * 0.2"
            ></div>
          </div>
        }

        <div class="loader__center"></div>

        @for (p of particles; track p.index) {
          <div
            class="loader__particle"
            [style.--p-x1.px]="p.x1"
            [style.--p-y1.px]="p.y1"
            [style.--p-x2.px]="p.x2"
            [style.--p-y2.px]="p.y2"
            [style.--p-x3.px]="p.x3"
            [style.--p-y3.px]="p.y3"
            [style.animation-duration.s]="p.duration"
            [style.animation-delay.s]="p.delay"
          ></div>
        }
      </div>

      <div class="loader__status">
        <span class="loader__word" [attr.data-key]="wordIndex()">
          {{ words[wordIndex()] }}
        </span>
        <span class="loader__dots">
          <span class="loader__dot-char loader__dot-char--1">.</span>
          <span class="loader__dot-char loader__dot-char--2">.</span>
          <span class="loader__dot-char loader__dot-char--3">.</span>
        </span>
      </div>

      <div class="loader__progress">
        <div class="loader__progress-fill"></div>
      </div>
    </div>
  `,
})
export class LoadingSpinnerComponent implements OnInit {
  private destroyRef = inject(DestroyRef);

  readonly words = STATUS_WORDS;
  readonly wordIndex = signal(0);
  readonly orbIndices = Array.from({ length: NUM_ORBS }, (_, i) => i);
  readonly particles: ParticleStyle[] = Array.from({ length: NUM_PARTICLES }, (_, i) => {
    const angle = (i / NUM_PARTICLES) * 360;
    const radius = 44 + (i % 3) * 8;
    const toRad = (deg: number) => (deg * Math.PI) / 180;
    return {
      index: i,
      x1: Math.cos(toRad(angle)) * radius,
      y1: Math.sin(toRad(angle)) * radius,
      x2: Math.cos(toRad(angle + 60)) * (radius + 10),
      y2: Math.sin(toRad(angle + 60)) * (radius + 10),
      x3: Math.cos(toRad(angle + 120)) * radius,
      y3: Math.sin(toRad(angle + 120)) * radius,
      duration: 3 + (i % 3),
      delay: i * 0.4,
    };
  });

  ngOnInit(): void {
    const id = setInterval(() => {
      this.wordIndex.update((v) => (v + 1) % STATUS_WORDS.length);
    }, CYCLE_MS);
    this.destroyRef.onDestroy(() => clearInterval(id));
  }
}
