// frontend/src/components/UserManagement/UserManagement.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { User } from '../../types';
import { fetchUsers, createUserApi, updateUserApi, deleteUserApi } from '../../services/api';
import { Button } from '../common/Button';
import './UserManagement.css';

interface ModalState {
  open: boolean;
  mode: 'add' | 'edit';
  user?: User;
}

interface FormData {
  name: string;
  email: string;
  role: string;
  password: string;
  is_active: boolean;
}

const emptyForm: FormData = { name: '', email: '', role: 'associate', password: '', is_active: true };

export function UserManagement() {
  const [users, setUsers] = useState<User[]>([]);
  const [loading, setLoading] = useState(true);
  const [modal, setModal] = useState<ModalState>({ open: false, mode: 'add' });
  const [form, setForm] = useState<FormData>(emptyForm);
  const [modalError, setModalError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  const loadUsers = useCallback(async () => {
    try {
      const data = await fetchUsers();
      setUsers(data);
    } catch {
      // Silently fail; users can retry
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadUsers();
  }, [loadUsers]);

  const openAdd = () => {
    setForm(emptyForm);
    setModalError(null);
    setModal({ open: true, mode: 'add' });
  };

  const openEdit = (user: User) => {
    setForm({
      name: user.name,
      email: user.email,
      role: user.role,
      password: '',
      is_active: user.is_active !== false,
    });
    setModalError(null);
    setModal({ open: true, mode: 'edit', user });
  };

  const closeModal = () => {
    setModal({ open: false, mode: 'add' });
    setModalError(null);
  };

  const handleSave = async () => {
    setModalError(null);

    if (!form.name.trim()) {
      setModalError('Name is required');
      return;
    }
    if (modal.mode === 'add' && !form.email.trim()) {
      setModalError('Email is required');
      return;
    }
    if (form.role === 'admin' && modal.mode === 'add' && !form.password) {
      setModalError('Password is required for admin accounts');
      return;
    }

    setSaving(true);
    try {
      if (modal.mode === 'add') {
        await createUserApi({
          name: form.name.trim(),
          email: form.email.trim(),
          role: form.role,
          password: form.password || undefined,
        });
      } else if (modal.user) {
        await updateUserApi(modal.user.id, {
          name: form.name.trim(),
          role: form.role,
          password: form.password || undefined,
          is_active: form.is_active,
        });
      }
      closeModal();
      await loadUsers();
    } catch (err: any) {
      setModalError(err.message || 'Failed to save user');
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async (user: User) => {
    if (!window.confirm(`Delete user "${user.name}" (${user.email})?`)) return;
    try {
      await deleteUserApi(user.id);
      await loadUsers();
    } catch {
      // Silently fail
    }
  };

  return (
    <div className="user-mgmt">
      <div className="user-mgmt__header">
        <div>
          <h2 className="user-mgmt__title">User Management</h2>
          <p className="user-mgmt__subtitle">Manage users and their roles</p>
        </div>
        <Button variant="primary" onClick={openAdd}>
          + Add User
        </Button>
      </div>

      {loading ? (
        <p className="user-mgmt__empty">Loading users...</p>
      ) : users.length === 0 ? (
        <p className="user-mgmt__empty">No users found</p>
      ) : (
        <div className="user-mgmt__list">
          <AnimatePresence>
            {users.map((user) => (
              <motion.div
                key={user.id}
                className="user-mgmt__user-card"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.2 }}
                layout
              >
                <div className="user-mgmt__user-info">
                  <span className="user-mgmt__user-name">{user.name}</span>
                  <span className="user-mgmt__user-email">{user.email}</span>
                </div>
                <div className="user-mgmt__user-badges">
                  <span
                    className={`user-mgmt__role-badge user-mgmt__role-badge--${user.role}`}
                  >
                    {user.role}
                  </span>
                  <span
                    className={`user-mgmt__status-dot user-mgmt__status-dot--${
                      user.is_active !== false ? 'active' : 'inactive'
                    }`}
                    title={user.is_active !== false ? 'Active' : 'Inactive'}
                  />
                </div>
                <div className="user-mgmt__user-actions">
                  <Button variant="ghost" onClick={() => openEdit(user)}>
                    Edit
                  </Button>
                  <Button variant="danger" onClick={() => handleDelete(user)}>
                    Delete
                  </Button>
                </div>
              </motion.div>
            ))}
          </AnimatePresence>
        </div>
      )}

      {/* Modal */}
      <AnimatePresence>
        {modal.open && (
          <motion.div
            className="user-mgmt__modal-overlay"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            onClick={closeModal}
          >
            <motion.div
              className="user-mgmt__modal"
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              transition={{ duration: 0.25, ease: [0.25, 0.46, 0.45, 0.94] }}
              onClick={(e) => e.stopPropagation()}
            >
              <h3 className="user-mgmt__modal-title">
                {modal.mode === 'add' ? 'Add User' : 'Edit User'}
              </h3>

              <div className="user-mgmt__modal-form">
                <div className="user-mgmt__field">
                  <label className="user-mgmt__field-label">Name</label>
                  <input
                    className="user-mgmt__field-input"
                    placeholder="Full name"
                    value={form.name}
                    onChange={(e) => setForm({ ...form, name: e.target.value })}
                    autoFocus
                  />
                </div>

                <div className="user-mgmt__field">
                  <label className="user-mgmt__field-label">Email</label>
                  <input
                    className="user-mgmt__field-input"
                    type="email"
                    placeholder="user@company.com"
                    value={form.email}
                    onChange={(e) => setForm({ ...form, email: e.target.value })}
                    disabled={modal.mode === 'edit'}
                  />
                </div>

                <div className="user-mgmt__field">
                  <label className="user-mgmt__field-label">Role</label>
                  <select
                    className="user-mgmt__field-select"
                    value={form.role}
                    onChange={(e) => setForm({ ...form, role: e.target.value })}
                  >
                    <option value="associate">Associate</option>
                    <option value="admin">Admin</option>
                  </select>
                </div>

                {form.role === 'admin' && (
                  <motion.div
                    className="user-mgmt__field"
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: 'auto' }}
                    exit={{ opacity: 0, height: 0 }}
                    transition={{ duration: 0.2 }}
                  >
                    <label className="user-mgmt__field-label">
                      Password {modal.mode === 'edit' && '(leave blank to keep current)'}
                    </label>
                    <input
                      className="user-mgmt__field-input"
                      type="password"
                      placeholder={modal.mode === 'edit' ? 'Unchanged' : 'Enter password'}
                      value={form.password}
                      onChange={(e) => setForm({ ...form, password: e.target.value })}
                    />
                  </motion.div>
                )}

                {modal.mode === 'edit' && (
                  <div className="user-mgmt__field">
                    <label className="user-mgmt__field-label">Status</label>
                    <select
                      className="user-mgmt__field-select"
                      value={form.is_active ? 'active' : 'inactive'}
                      onChange={(e) =>
                        setForm({ ...form, is_active: e.target.value === 'active' })
                      }
                    >
                      <option value="active">Active</option>
                      <option value="inactive">Inactive</option>
                    </select>
                  </div>
                )}

                {modalError && (
                  <motion.div
                    className="user-mgmt__modal-error"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                  >
                    {modalError}
                  </motion.div>
                )}

                <div className="user-mgmt__modal-actions">
                  <Button variant="ghost" onClick={closeModal} disabled={saving}>
                    Cancel
                  </Button>
                  <Button variant="primary" onClick={handleSave} disabled={saving}>
                    {saving ? 'Saving...' : 'Save'}
                  </Button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// frontend-angular/src/app/features/user-management/user-management.component.ts
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ViewEncapsulation,
  inject,
  signal,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';

import { ApiService } from '../../core/services/api.service';
import { ButtonComponent } from '../../shared/ui/button.component';
import { User } from '../../core/types';

interface FormData {
  name: string;
  email: string;
  role: 'admin' | 'associate';
  password: string;
  is_active: boolean;
}

const EMPTY_FORM: FormData = {
  name: '',
  email: '',
  role: 'associate',
  password: '',
  is_active: true,
};

/**
 * Admin-only user CRUD page. Same UX as the React UserManagement component:
 * a row list with role badges + status dot, plus a centered modal for
 * add/edit. Modal uses ngModel two-way binding for form fields.
 */
@Component({
  selector: 'app-user-management',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  imports: [FormsModule, ButtonComponent],
  styleUrl: './user-management.component.css',
  template: `
    <div class="user-mgmt">
      <div class="user-mgmt__header">
        <div>
          <h2 class="user-mgmt__title">User Management</h2>
          <p class="user-mgmt__subtitle">Manage users and their roles</p>
        </div>
        <app-button variant="primary" (click)="openAdd()">+ Add User</app-button>
      </div>

      @if (loading()) {
        <p class="user-mgmt__empty">Loading users...</p>
      } @else if (users().length === 0) {
        <p class="user-mgmt__empty">No users found</p>
      } @else {
        <div class="user-mgmt__list">
          @for (user of users(); track user.id) {
            <div class="user-mgmt__user-card">
              <div class="user-mgmt__user-info">
                <span class="user-mgmt__user-name">{{ user.name }}</span>
                <span class="user-mgmt__user-email">{{ user.email }}</span>
              </div>
              <div class="user-mgmt__user-badges">
                <span
                  class="user-mgmt__role-badge"
                  [class.user-mgmt__role-badge--admin]="user.role === 'admin'"
                  [class.user-mgmt__role-badge--associate]="user.role === 'associate'"
                >
                  {{ user.role }}
                </span>
                <span
                  class="user-mgmt__status-dot"
                  [class.user-mgmt__status-dot--active]="user.is_active !== false"
                  [class.user-mgmt__status-dot--inactive]="user.is_active === false"
                  [title]="user.is_active !== false ? 'Active' : 'Inactive'"
                ></span>
              </div>
              <div class="user-mgmt__user-actions">
                <app-button variant="ghost" (click)="openEdit(user)">Edit</app-button>
                <app-button variant="danger" (click)="confirmDelete(user)">
                  Delete
                </app-button>
              </div>
            </div>
          }
        </div>
      }

      @if (modalOpen()) {
        <div class="user-mgmt__modal-overlay" (click)="closeModal()">
          <div class="user-mgmt__modal" (click)="$event.stopPropagation()">
            <h3 class="user-mgmt__modal-title">
              {{ modalMode() === 'add' ? 'Add User' : 'Edit User' }}
            </h3>

            <div class="user-mgmt__modal-form">
              <div class="user-mgmt__field">
                <label class="user-mgmt__field-label">Name</label>
                <input
                  class="user-mgmt__field-input"
                  placeholder="Full name"
                  [(ngModel)]="form.name"
                  name="name"
                  autofocus
                />
              </div>

              <div class="user-mgmt__field">
                <label class="user-mgmt__field-label">Email</label>
                <input
                  class="user-mgmt__field-input"
                  type="email"
                  placeholder="user@company.com"
                  [(ngModel)]="form.email"
                  name="email"
                  [disabled]="modalMode() === 'edit'"
                />
              </div>

              <div class="user-mgmt__field">
                <label class="user-mgmt__field-label">Role</label>
                <select
                  class="user-mgmt__field-select"
                  [(ngModel)]="form.role"
                  name="role"
                >
                  <option value="associate">Associate</option>
                  <option value="admin">Admin</option>
                </select>
              </div>

              @if (form.role === 'admin') {
                <div class="user-mgmt__field user-mgmt__field--anim">
                  <label class="user-mgmt__field-label">
                    Password{{ modalMode() === 'edit' ? ' (leave blank to keep current)' : '' }}
                  </label>
                  <input
                    class="user-mgmt__field-input"
                    type="password"
                    [placeholder]="modalMode() === 'edit' ? 'Unchanged' : 'Enter password'"
                    [(ngModel)]="form.password"
                    name="password"
                  />
                </div>
              }

              @if (modalMode() === 'edit') {
                <div class="user-mgmt__field">
                  <label class="user-mgmt__field-label">Status</label>
                  <select
                    class="user-mgmt__field-select"
                    [ngModel]="form.is_active ? 'active' : 'inactive'"
                    (ngModelChange)="form.is_active = $event === 'active'"
                    name="status"
                  >
                    <option value="active">Active</option>
                    <option value="inactive">Inactive</option>
                  </select>
                </div>
              }

              @if (modalError(); as err) {
                <div class="user-mgmt__modal-error">{{ err }}</div>
              }

              <div class="user-mgmt__modal-actions">
                <app-button
                  variant="ghost"
                  [disabled]="saving()"
                  (click)="closeModal()"
                >
                  Cancel
                </app-button>
                <app-button
                  variant="primary"
                  [disabled]="saving()"
                  (click)="onSave()"
                >
                  {{ saving() ? 'Saving...' : 'Save' }}
                </app-button>
              </div>
            </div>
          </div>
        </div>
      }
    </div>
  `,
})
export class UserManagementComponent {
  private api = inject(ApiService);
  private cdr = inject(ChangeDetectorRef);

  protected users = signal<User[]>([]);
  protected loading = signal<boolean>(true);
  protected modalOpen = signal<boolean>(false);
  protected modalMode = signal<'add' | 'edit'>('add');
  protected editingUser = signal<User | null>(null);
  protected modalError = signal<string | null>(null);
  protected saving = signal<boolean>(false);

  protected form: FormData = { ...EMPTY_FORM };

  constructor() {
    void this.loadUsers();
  }

  private async loadUsers(): Promise<void> {
    this.loading.set(true);
    try {
      const data = await firstValueFrom(this.api.fetchUsers());
      this.users.set(data);
    } catch {
      /* ignore */
    } finally {
      this.loading.set(false);
      this.cdr.markForCheck();
    }
  }

  openAdd(): void {
    this.form = { ...EMPTY_FORM };
    this.modalError.set(null);
    this.modalMode.set('add');
    this.editingUser.set(null);
    this.modalOpen.set(true);
  }

  openEdit(user: User): void {
    this.form = {
      name: user.name,
      email: user.email,
      role: user.role,
      password: '',
      is_active: user.is_active !== false,
    };
    this.modalError.set(null);
    this.modalMode.set('edit');
    this.editingUser.set(user);
    this.modalOpen.set(true);
  }

  closeModal(): void {
    this.modalOpen.set(false);
    this.modalError.set(null);
  }

  async onSave(): Promise<void> {
    this.modalError.set(null);

    if (!this.form.name.trim()) {
      this.modalError.set('Name is required');
      return;
    }
    if (this.modalMode() === 'add' && !this.form.email.trim()) {
      this.modalError.set('Email is required');
      return;
    }
    if (
      this.form.role === 'admin' &&
      this.modalMode() === 'add' &&
      !this.form.password
    ) {
      this.modalError.set('Password is required for admin accounts');
      return;
    }

    this.saving.set(true);
    try {
      if (this.modalMode() === 'add') {
        await firstValueFrom(
          this.api.createUser({
            name: this.form.name.trim(),
            email: this.form.email.trim(),
            role: this.form.role,
            password: this.form.password || undefined,
          }),
        );
      } else {
        const editing = this.editingUser();
        if (editing) {
          await firstValueFrom(
            this.api.updateUser(editing.id, {
              name: this.form.name.trim(),
              role: this.form.role,
              password: this.form.password || undefined,
              is_active: this.form.is_active,
            }),
          );
        }
      }
      this.closeModal();
      await this.loadUsers();
    } catch (err: unknown) {
      this.modalError.set(err instanceof Error ? err.message : 'Failed to save user');
    } finally {
      this.saving.set(false);
    }
  }

  async confirmDelete(user: User): Promise<void> {
    if (!window.confirm(`Delete user "${user.name}" (${user.email})?`)) return;
    try {
      await firstValueFrom(this.api.deleteUser(user.id));
      await this.loadUsers();
    } catch {
      /* ignore */
    }
  }
}
