// frontend/src/components/ResponsePanel/ResponsePanel.tsx
import React, { useState, useCallback, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useAppState, useAppDispatch } from '../../context/AppContext';
import { updateHistoryItem } from '../../services/api';
import { Button } from '../common/Button';
import './ResponsePanel.css';

type Tab = 'response' | 'reasoning' | 'sources';

export function ResponsePanel() {
  const { editedResponse, response, reasoning, sources, selectedConversationId } = useAppState();
  const dispatch = useAppDispatch();
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState(false);
  const [saving, setSaving] = useState(false);
  const [activeTab, setActiveTab] = useState<Tab>('response');
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const isEdited = editedResponse !== response;

  const handleChange = useCallback((e: React.ChangeEvent<HTMLTextAreaElement>) => {
    dispatch({ type: 'SET_EDITED_RESPONSE', payload: e.target.value });
    const el = e.target;
    el.style.height = 'auto';
    el.style.height = el.scrollHeight + 'px';
  }, [dispatch]);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(editedResponse);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      textareaRef.current?.select();
    }
  }, [editedResponse]);

  const handleSave = useCallback(async () => {
    if (!selectedConversationId || saving) return;
    setSaving(true);
    try {
      await updateHistoryItem(selectedConversationId, editedResponse);
      dispatch({
        type: 'UPDATE_CONVERSATION_RESPONSE',
        payload: { id: selectedConversationId, response: editedResponse },
      });
      setSaved(true);
      setTimeout(() => setSaved(false), 2000);
    } catch {}
    setSaving(false);
  }, [selectedConversationId, editedResponse, saving, dispatch]);

  useEffect(() => {
    const el = textareaRef.current;
    if (el) {
      el.style.height = 'auto';
      el.style.height = el.scrollHeight + 'px';
    }
  }, [editedResponse]);

  return (
    <div className="response-panel">
      <div className="response-panel__header">
        <div className="response-panel__tabs">
          <button
            className={`response-panel__tab ${activeTab === 'response' ? 'response-panel__tab--active' : ''}`}
            onClick={() => setActiveTab('response')}
          >
            Response
          </button>
          <button
            className={`response-panel__tab ${activeTab === 'reasoning' ? 'response-panel__tab--active' : ''}`}
            onClick={() => setActiveTab('reasoning')}
          >
            Reasoning
          </button>
          <button
            className={`response-panel__tab ${activeTab === 'sources' ? 'response-panel__tab--active' : ''}`}
            onClick={() => setActiveTab('sources')}
          >
            Sources{sources.length > 0 && ` (${sources.length})`}
          </button>
        </div>
        {activeTab === 'response' && (
          <div className="response-panel__actions">
            <AnimatePresence>
              {isEdited && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.9, x: 8 }}
                  animate={{ opacity: 1, scale: 1, x: 0 }}
                  exit={{ opacity: 0, scale: 0.9, x: 8 }}
                  transition={{ duration: 0.2 }}
                  whileTap={{ scale: 0.95 }}
                >
                  <Button
                    variant="primary"
                    className="response-panel__save-btn"
                    onClick={handleSave}
                    disabled={saving}
                  >
                    <AnimatePresence mode="wait">
                      <motion.span
                        key={saved ? 'saved' : saving ? 'saving' : 'save'}
                        initial={{ opacity: 0, y: 6 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -6 }}
                        transition={{ duration: 0.15 }}
                      >
                        {saved ? 'Saved!' : saving ? 'Saving...' : 'Save'}
                      </motion.span>
                    </AnimatePresence>
                  </Button>
                </motion.div>
              )}
            </AnimatePresence>
            <motion.div whileTap={{ scale: 0.95 }}>
              <Button
                variant="success"
                className="response-panel__copy-btn"
                onClick={handleCopy}
              >
                <AnimatePresence mode="wait">
                  <motion.span
                    key={copied ? 'copied' : 'copy'}
                    initial={{ opacity: 0, y: 6 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -6 }}
                    transition={{ duration: 0.15 }}
                  >
                    {copied ? 'Copied!' : 'Copy'}
                  </motion.span>
                </AnimatePresence>
              </Button>
            </motion.div>
          </div>
        )}
      </div>

      {activeTab === 'response' && (
        <>
          <textarea
            ref={textareaRef}
            className="response-panel__textarea"
            value={editedResponse}
            onChange={handleChange}
            spellCheck={false}
          />
          <p className="response-panel__hint">
            {isEdited ? 'You have unsaved edits — click Save to update' : 'Edit the response above before copying'}
          </p>
        </>
      )}

      {activeTab === 'reasoning' && (
        <div className="response-panel__reasoning">
          {reasoning ? reasoning : 'No reasoning available for this response.'}
        </div>
      )}

      {activeTab === 'sources' && (
        <div className="response-panel__sources">
          {sources.length === 0 ? (
            <p className="response-panel__sources-empty">No sources retrieved.</p>
          ) : (
            sources.map((src, i) => (
              <div key={i} className="response-panel__source-card">
                <div className="response-panel__source-header">
                  <span className="response-panel__source-badge">{src.category}</span>
                  <span className="response-panel__source-score">
                    {(src.relevance_score * 100).toFixed(0)}% match
                  </span>
                </div>
                <p className="response-panel__source-desc">{src.description}</p>
                <p className="response-panel__source-response">{src.response}</p>
              </div>
            ))
          )}
        </div>
      )}
    </div>
  );
}

// frontend/src/app/shared/response-panel/response-panel.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  ViewChild,
  ViewEncapsulation,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';
import { AppStateService } from '../../core/services/app-state.service';
import { ButtonComponent } from '../ui/button.component';

type Tab = 'response' | 'reasoning' | 'sources';

@Component({
  selector: 'app-response-panel',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  imports: [ButtonComponent],
  styleUrl: './response-panel.component.css',
  template: `
    <div class="response-panel">
      <div class="response-panel__header">
        <div class="response-panel__tabs">
          <button
            type="button"
            class="response-panel__tab"
            [class.response-panel__tab--active]="activeTab() === 'response'"
            (click)="activeTab.set('response')"
          >
            Response
          </button>
          <button
            type="button"
            class="response-panel__tab"
            [class.response-panel__tab--active]="activeTab() === 'reasoning'"
            (click)="activeTab.set('reasoning')"
          >
            Reasoning
          </button>
          <button
            type="button"
            class="response-panel__tab"
            [class.response-panel__tab--active]="activeTab() === 'sources'"
            (click)="activeTab.set('sources')"
          >
            Sources@if (state.sources().length > 0) { ({{ state.sources().length }}) }
          </button>
        </div>

        @if (activeTab() === 'response') {
          <div class="response-panel__actions">
            @if (isEdited()) {
              <app-button
                variant="primary"
                [disabled]="saving()"
                (click)="onSave()"
              >
                {{ saved() ? 'Saved!' : saving() ? 'Saving...' : 'Save' }}
              </app-button>
            }
            <app-button variant="success" (click)="onCopy()">
              {{ copied() ? 'Copied!' : 'Copy' }}
            </app-button>
          </div>
        }
      </div>

      @switch (activeTab()) {
        @case ('response') {
          <textarea
            #textarea
            class="response-panel__textarea"
            spellcheck="false"
            [value]="state.editedResponse()"
            (input)="onInput($event)"
          ></textarea>
          <p class="response-panel__hint">
            {{
              isEdited()
                ? 'You have unsaved edits — click Save to update'
                : 'Edit the response above before copying'
            }}
          </p>
        }

        @case ('reasoning') {
          <div class="response-panel__reasoning">
            {{ state.reasoning() ?? 'No reasoning available for this response.' }}
          </div>
        }

        @case ('sources') {
          <div class="response-panel__sources">
            @if (state.sources().length === 0) {
              <p class="response-panel__sources-empty">No sources retrieved.</p>
            } @else {
              @for (src of state.sources(); track $index) {
                <div class="response-panel__source-card">
                  <div class="response-panel__source-header">
                    <span class="response-panel__source-badge">{{ src.category }}</span>
                    <span class="response-panel__source-score">
                      {{ (src.relevance_score * 100).toFixed(0) }}% match
                    </span>
                  </div>
                  <p class="response-panel__source-desc">{{ src.description }}</p>
                  <p class="response-panel__source-response">{{ src.response }}</p>
                </div>
              }
            }
          </div>
        }
      }
    </div>
  `,
})
export class ResponsePanelComponent implements AfterViewInit {
  protected state = inject(AppStateService);
  private cdr = inject(ChangeDetectorRef);

  @ViewChild('textarea') textareaRef?: ElementRef<HTMLTextAreaElement>;

  protected activeTab = signal<Tab>('response');
  protected copied = signal(false);
  protected saved = signal(false);
  protected saving = signal(false);

  protected isEdited = computed(
    () => this.state.editedResponse() !== this.state.response(),
  );

  constructor() {
    // Whenever editedResponse changes (via load or external set), reflow the textarea.
    effect(() => {
      // touch the signal so the effect re-runs on change
      void this.state.editedResponse();
      queueMicrotask(() => this.autoResize());
    });
  }

  ngAfterViewInit(): void {
    this.autoResize();
  }

  private autoResize(): void {
    const el = this.textareaRef?.nativeElement;
    if (!el) return;
    el.style.height = 'auto';
    el.style.height = `${el.scrollHeight}px`;
  }

  onInput(event: Event): void {
    const el = event.target as HTMLTextAreaElement;
    this.state.setEditedResponse(el.value);
    el.style.height = 'auto';
    el.style.height = `${el.scrollHeight}px`;
  }

  async onCopy(): Promise<void> {
    try {
      await navigator.clipboard.writeText(this.state.editedResponse());
      this.copied.set(true);
      setTimeout(() => {
        this.copied.set(false);
        this.cdr.markForCheck();
      }, 2000);
    } catch {
      this.textareaRef?.nativeElement.select();
    }
  }

  async onSave(): Promise<void> {
    const id = this.state.selectedConversationId();
    if (!id || this.saving()) return;
    this.saving.set(true);
    try {
      await this.state.updateConversationResponse(id, this.state.editedResponse());
      this.saved.set(true);
      setTimeout(() => {
        this.saved.set(false);
        this.cdr.markForCheck();
      }, 2000);
    } catch {
      /* ignore */
    } finally {
      this.saving.set(false);
    }
  }
}
